package com.itchao.tchao_blog.pojo;

import java.io.Serializable;
import java.util.Date;

public class BookNote implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.read_num
     *
     * @mbggenerated
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.comment_num
     *
     * @mbggenerated
     */
    private Integer commentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.like_num
     *
     * @mbggenerated
     */
    private Integer likeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.book_id
     *
     * @mbggenerated
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.chapter
     *
     * @mbggenerated
     */
    private String chapter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.recommend
     *
     * @mbggenerated
     */
    private Boolean recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.category_id
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.publish
     *
     * @mbggenerated
     */
    private Byte publish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.cover_type
     *
     * @mbggenerated
     */
    private Integer coverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_note.top
     *
     * @mbggenerated
     */
    private Boolean top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_note
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.id
     *
     * @return the value of book_note.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.id
     *
     * @param id the value for book_note.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.title
     *
     * @return the value of book_note.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.title
     *
     * @param title the value for book_note.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.author
     *
     * @return the value of book_note.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.author
     *
     * @param author the value for book_note.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.read_num
     *
     * @return the value of book_note.read_num
     *
     * @mbggenerated
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.read_num
     *
     * @param readNum the value for book_note.read_num
     *
     * @mbggenerated
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.comment_num
     *
     * @return the value of book_note.comment_num
     *
     * @mbggenerated
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.comment_num
     *
     * @param commentNum the value for book_note.comment_num
     *
     * @mbggenerated
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.like_num
     *
     * @return the value of book_note.like_num
     *
     * @mbggenerated
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.like_num
     *
     * @param likeNum the value for book_note.like_num
     *
     * @mbggenerated
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.book_id
     *
     * @return the value of book_note.book_id
     *
     * @mbggenerated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.book_id
     *
     * @param bookId the value for book_note.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.chapter
     *
     * @return the value of book_note.chapter
     *
     * @mbggenerated
     */
    public String getChapter() {
        return chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.chapter
     *
     * @param chapter the value for book_note.chapter
     *
     * @mbggenerated
     */
    public void setChapter(String chapter) {
        this.chapter = chapter == null ? null : chapter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.create_time
     *
     * @return the value of book_note.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.create_time
     *
     * @param createTime the value for book_note.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.update_time
     *
     * @return the value of book_note.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.update_time
     *
     * @param updateTime the value for book_note.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.recommend
     *
     * @return the value of book_note.recommend
     *
     * @mbggenerated
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.recommend
     *
     * @param recommend the value for book_note.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.category_id
     *
     * @return the value of book_note.category_id
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.category_id
     *
     * @param categoryId the value for book_note.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.publish
     *
     * @return the value of book_note.publish
     *
     * @mbggenerated
     */
    public Byte getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.publish
     *
     * @param publish the value for book_note.publish
     *
     * @mbggenerated
     */
    public void setPublish(Byte publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.cover_type
     *
     * @return the value of book_note.cover_type
     *
     * @mbggenerated
     */
    public Integer getCoverType() {
        return coverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.cover_type
     *
     * @param coverType the value for book_note.cover_type
     *
     * @mbggenerated
     */
    public void setCoverType(Integer coverType) {
        this.coverType = coverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_note.top
     *
     * @return the value of book_note.top
     *
     * @mbggenerated
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_note.top
     *
     * @param top the value for book_note.top
     *
     * @mbggenerated
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_note
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", author=").append(author);
        sb.append(", readNum=").append(readNum);
        sb.append(", commentNum=").append(commentNum);
        sb.append(", likeNum=").append(likeNum);
        sb.append(", bookId=").append(bookId);
        sb.append(", chapter=").append(chapter);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", recommend=").append(recommend);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", publish=").append(publish);
        sb.append(", coverType=").append(coverType);
        sb.append(", top=").append(top);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}