package com.itchao.tchao_blog.pojo;

import java.io.Serializable;

public class SysParam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.par_key
     *
     * @mbggenerated
     */
    private Integer parKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.par_value
     *
     * @mbggenerated
     */
    private String parValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.menu_url
     *
     * @mbggenerated
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_param
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.id
     *
     * @return the value of sys_param.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.id
     *
     * @param id the value for sys_param.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.par_key
     *
     * @return the value of sys_param.par_key
     *
     * @mbggenerated
     */
    public Integer getParKey() {
        return parKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.par_key
     *
     * @param parKey the value for sys_param.par_key
     *
     * @mbggenerated
     */
    public void setParKey(Integer parKey) {
        this.parKey = parKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.par_value
     *
     * @return the value of sys_param.par_value
     *
     * @mbggenerated
     */
    public String getParValue() {
        return parValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.par_value
     *
     * @param parValue the value for sys_param.par_value
     *
     * @mbggenerated
     */
    public void setParValue(String parValue) {
        this.parValue = parValue == null ? null : parValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.menu_url
     *
     * @return the value of sys_param.menu_url
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.menu_url
     *
     * @param menuUrl the value for sys_param.menu_url
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.type
     *
     * @return the value of sys_param.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.type
     *
     * @param type the value for sys_param.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parKey=").append(parKey);
        sb.append(", parValue=").append(parValue);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}