package com.itchao.tchao_blog.dao;

import com.itchao.tchao_blog.pojo.BookSense;
import com.itchao.tchao_blog.pojo.BookSenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookSenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int countByExample(BookSenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int deleteByExample(BookSenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int insert(BookSense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int insertSelective(BookSense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    List<BookSense> selectByExampleWithBLOBs(BookSenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    List<BookSense> selectByExample(BookSenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    BookSense selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookSense record, @Param("example") BookSenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BookSense record, @Param("example") BookSenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookSense record, @Param("example") BookSenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookSense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BookSense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_sense
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookSense record);
}