package com.itchao.tchao_blog.dao;

import com.itchao.tchao_blog.pojo.LogView;
import com.itchao.tchao_blog.pojo.LogViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int countByExample(LogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int deleteByExample(LogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int insert(LogView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int insertSelective(LogView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    List<LogView> selectByExample(LogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    LogView selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LogView record, @Param("example") LogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LogView record, @Param("example") LogViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogView record);
}