package com.itchao.tchao_blog.dao;

import com.itchao.tchao_blog.pojo.OssResource;
import com.itchao.tchao_blog.pojo.OssResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OssResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int countByExample(OssResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int deleteByExample(OssResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int insert(OssResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int insertSelective(OssResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    List<OssResource> selectByExample(OssResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    OssResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OssResource record, @Param("example") OssResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OssResource record, @Param("example") OssResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OssResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OssResource record);
}