package com.itchao.tchao_blog.dao;

import com.itchao.tchao_blog.pojo.Recommend;
import com.itchao.tchao_blog.pojo.RecommendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int countByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int deleteByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int insertSelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    List<Recommend> selectByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    Recommend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recommend record);
}