package com.itchao.tchao_blog.dao;

import com.itchao.tchao_blog.pojo.TagLink;
import com.itchao.tchao_blog.pojo.TagLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int countByExample(TagLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int deleteByExample(TagLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int insert(TagLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int insertSelective(TagLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    List<TagLink> selectByExample(TagLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    TagLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TagLink record, @Param("example") TagLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TagLink record, @Param("example") TagLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TagLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TagLink record);
}